name: tashkentcityresturant
description: "Tashkent City Restaurant App"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  yandex_mapkit:
  url_launcher:
  geocoding:
  device_info:
  easy_localization:
  fluttertoast:
  cached_network_image: ^3.3.1
  animated_toggle_switch:
  sms_autofill:
  pinput:
  calendar_date_picker2:
  story_view:
  device_info_plus:
  flutter_riverpod:
  auto_size_text:
  cupertino_modal_sheet:
  modal_bottom_sheet:
  gif:

  freezed_annotation:
  mask_text_input_formatter:
  shared_preferences:
  dotted_line:
  blur:
  jwt_decoder:
  web_socket_channel:
  hive:
  collection:
  path_provider:
  flutter_rating_bar:
  geolocator:
  share_plus:
  bloc:
  flutter_bloc:
  qr_code_scanner:
  permission_handler:
  hive_flutter:
  just_the_tooltip:

  flutter_svg:

  cupertino_icons:
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  freezed:
  build_runner:
  hive_generator:
  auto_route_generator:



  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"


flutter:


  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/my_icons/
    - assets/images/
    - assets/gif/
    - assets/translations/


  fonts:
      - family: Adonis
        fonts:
          - asset: assets/fonts/Adonis_Bold.otf
            weight: 600
          - asset: assets/fonts/Adonis_Bold.otf
            weight: 500
          - asset: assets/fonts/Adonis_Regular.otf
            weight: 400



